name: govcookiecutter template build

on:
  push:
    branches:
      - workflow_tests
jobs:
  template-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ 3.9, '3.11' ]
        R:
#          - {using_R: No, version: N/A}
          - {using_R: Yes, version: 4.2.3}
          - {using_R: Yes, version: 4.3.3}
          - {using_R: Yes, version: 4.4.3}
    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4
        with:
          path: ga-govcookiecutter
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
