name: govcookiecutter template build

on:
  push:
    branches:
      - workflow_tests
jobs:
  template-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4
        with:
          path: ga-govcookiecutter
