name: govcookiecutter template build

on:
  push:
    branches:
      - workflow_tests
jobs:
  template-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [ 3.9, '3.11' ]
    steps:
      - name: Checkout the revision
        uses: actions/checkout@v4
        with:
          path: ga-govcookiecutter
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
